PROJECT_NAME = UM3

all: UM3.cpp parser.cpp Memory.cpp Processor.cpp Exception.cpp
	g++ -o $(PROJECT_NAME) UM3.cpp parser.cpp Memory.cpp Processor.cpp Exception.cpp

clean:
	rm *.o

run:
	./$(PROGRAM)

